int c;
char r;
int _islower(int c);
char _putchar(char r);
int _isalpha(int c);
int print_sign(int n);
int _abs(int);
int print_last_digit(int);
void jack_bauer(void);
void times_table(void);
void print_times_table(int n);
int add(int, int);
void print_to_98(int n);
